#!/bin/bash -ex

mkdir build && cd build

cmake .. -G Ninja \
 -DCMAKE_BUILD_TYPE=Release \
 -DCMAKE_C_COMPILER=/usr/lib/ccache/gcc-9 \
 -DCMAKE_CXX_COMPILER=/usr/lib/ccache/g++-9 \
 -DENABLE_QT_TRANSLATION=ON \
 -DCITRA_ENABLE_COMPATIBILITY_REPORTING=OFF \
 -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=OFF \
 -DUSE_DISCORD_PRESENCE=OFF \
 -DENABLE_FFMPEG_VIDEO_DUMPER=ON \
 -DENABLE_MF=ON \
 -DCMAKE_NO_SYSTEM_FROM_IMPORTED=TRUE \
 -DCOMPILE_WITH_DWARF=OFF

ninja

ctest -VV -C Release