name: citra-ci

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  workflow_dispatch:
jobs:
  source:
    if: ${{ !github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Pack
        run: |
          chmod +x ./.ci/source.sh
          ./.ci/source.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: artifacts/
  windows:
    runs-on: windows-2022
    # strategy:
    #   matrix:
    #     arch:
    #       - x64
    #     sdk:
    #       - 10.0.19041.0
    #     toolset:
    #       - 19.16.27023
    #     vsversion:
    #       - '2022'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ~/.buildcache
          key: ${{ runner.os }}-win-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-win-
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        # with:
        #   arch: ${{ matrix.arch }}
        #   sdk: ${{ matrix.sdk }}
        #   toolset: ${{ matrix.toolset }}
        #   vsversion: ${{ matrix.vsversion }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        # with:
        #   msbuild-architecture: ${{ matrix.arch }}
      - name: Disable line ending translation
        run: git config --global core.autocrlf input
      - name: Build
        # run: ./.ci/windows.sh
        run: |
          mkdir build && cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -T v141 \
              -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
              -DCMAKE_BUILD_TYPE=Release \
              -DCITRA_USE_BUNDLED_QT=1 \
              -DCITRA_USE_BUNDLED_SDL2=1 \
              -DENABLE_QT_TRANSLATION=ON \
              -DCITRA_ENABLE_COMPATIBILITY_REPORTING=OFF \
              -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON \
              -DUSE_DISCORD_PRESENCE=ON \
              -DENABLE_FFMPEG_VIDEO_DUMPER=ON \
              -DENABLE_MF=ON
          msbuild build/citra.sln /m /p:Configuration=Release,Platform=x64 /t:Rebuild
          ctest -VV -C Release || echo "::error ::Test error occurred on Windows build"
      - name: Pack
        run: ./.ci/pack.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OS }}-${{ env.TARGET }}
          path: artifacts/
  release:
    runs-on: ubuntu-latest
    needs: [windows, source]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/download-artifact@v4
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload artifacts
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./**/*.tar.*","./**/*.AppImage","./**/*.7z","./**/*.zip","./**/*.apk","./**/*.aab"]'