name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: windows-2022
        toolset_ver:
          - "v140"
          - "v141"
          - 140
          - 141
          - 14
          - "14.0"
          - "14.1"
          - 14.1
          - 14.2
          - 14.21
          - 14.22
          - 14.23
          - 14.24
          - 14.25
          - 14.26
          - 14.27
          - 14.28
          - 14.29
          - "14.30"
          - 14.3
          - 14.31
          - 14.32
          - 14.33
          - 14.34
          - 14.35
          - 14.36
          - 14.37
          - 14.38
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: ${{ matrix.toolset_ver }}
      # https://learn.microsoft.com/cpp/build/reference/help-compiler-command-line-help
      - run: |
          "CL_VERSION=$(cl /? 2>&1 | Select-String -Pattern 'Compiler Version' -CaseSensitive -SimpleMatch)" | Out-File -Append -FilePath ${env:\GITHUB_OUTPUT}
        shell: pwsh
        id: cl
      - run: echo '::warning ::${{ matrix.os }} + toolset-${{ matrix.toolset_ver }} = ${{ steps.cl.outputs.CL_VERSION }}'
