name: MSVC-CI
on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  workflow_dispatch:
jobs:
  check_version:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MSVC 2017
        shell: pwsh
        run: |
          # workload 安装全部 required，component 单独组件
          # https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2022#desktop-development-with-c

          Write-Host "Installing MSVC v141"

          $vs_url = "https://aka.ms/vs/15/release/vs_BuildTools.exe"
          $components = @(
            "Microsoft.VisualStudio.Workload.VCTools",
            "Microsoft.VisualStudio.Component.Windows10SDK.19041",
            "Microsoft.VisualStudio.Component.VC.v141.x86.x64",
            "Microsoft.VisualStudio.Component.VC.CMake.Project"
          )

          # 下载安装器
          Invoke-WebRequest -Uri $vs_url -OutFile "vs_buildtools.exe"

          # 安装
          $componentArgs = $components | ForEach-Object { "--add `"$($_)`"" } -join " "
          $installCmd = ".\vs_buildtools.exe --quiet --wait --norestart --nocache --installPath C:\BuildTools $componentArgs"

          Write-Host "Running: $installCmd"
          iex $installCmd

      - name: 验证 cl 编译器版本
        shell: cmd
        run: |
          call "C:\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /Bv

      # - uses: ilammy/msvc-dev-cmd@v1
      #   with:
      #     arch: x64
      #     toolset: ${{ matrix.toolset_ver }}
      # # https://learn.microsoft.com/cpp/build/reference/help-compiler-command-line-help
      # - run: |
      #     "CL_VERSION=$(cl /? 2>&1 | Select-String -Pattern 'Compiler Version' -CaseSensitive -SimpleMatch)" | Out-File -Append -FilePath ${env:\GITHUB_OUTPUT}
      #   shell: pwsh
      #   id: cl
      # - run: echo '::warning ::${{ matrix.os }} + toolset-${{ matrix.toolset_ver }} = ${{ steps.cl.outputs.CL_VERSION }}'